### ISSUE TITLE
API URL ConnectException

### ISSUE THREAD

**Issue by ghost** [renespeck/fox-java#1]
Hi,

Is it possible to do **NER** using **Fox-Java**? The current status of execution throws _ConnectException_. 

**Commit**: https://github.com/SmartBV2/Fact_Checker/commit/3b4ebdab55bab570fc7b8e19c2d9c2d435934ba9

![fox api error](https://user-images.githubusercontent.com/17321286/35353992-2129537e-0149-11e8-9f88-8b96b76c7605.JPG)

Any ideas to fix? Could it be a problem with wrong API URL?

Thanks! in advance.

**Comment by renespeck** [comment]
I updated the version. 

Use the last version as noted in the `README.md`  and check the example `Examples.java` file.
